# Generated by Django 3.2.9 on 2021-12-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0005_visitorlog_status_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="visits_max",
            field=models.SmallIntegerField(
                blank=True, help_text="Set to blank for unlimited.", null=True
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="visits_remaining",
            field=models.SmallIntegerField(
                blank=True,
                help_text="Number of sessions left for this visitor",
                null=True,
            ),
        ),
    ]
